In [6]:
#example of basic matrix operation using NumPy
import numpy as np
#create matrices
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
#addition
C=A+B
#substraction
D=A-B
#multiplication (element-wise)
E=A*B
#matrix multiplication
F=np.dot(A,B) # A@B
#transpose
A_transpose=A.T
print("Addition:")
print(C)
print("\nSubstraction:")
print(D)
print("\nElement-wise Multiplication:")
print(E)
print("\nMatrix Multiplication:")
print(F)
print("\nTranspose:")
print(A_transpose)





#with SVD
import numpy as np
#create a sample matrix
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
#perform SVD
U,S,VT =np.linalg.svd(X)
#choose number of components to keep
n_components=2
#reconstruct the matrix with reduced dimensions
X_reconstructed =np.dot(U[:, :n_components],np.dot(np.diag(S[:n_components]),VT[:n_components, :]))
print("Original matrix:")
print(X)
print("\n reconstructed the matrix (with reduced dimensions):")
print(X_reconstructed)


Addition:
[[ 6  8]
 [10 12]]

Substraction:
[[-4 -4]
 [-4 -4]]

Element-wise Multiplication:
[[ 5 12]
 [21 32]]

Matrix Multiplication:
[[19 22]
 [43 50]]

Transpose:
[[1 3]
 [2 4]]
Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

 reconstructed the matrix (with reduced dimensions):
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
